name: becwilliamslife
favicon: null
layout_spectrum: 0.26245567156001925
typography_spectrum: 0.04679938708432019
title: Bec Williams LIFE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d35d13'
    - '#c40030'
    - '#ce491a'
    - '#c6112c'
    - '#ca2d22'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
