name: becwilliamslife
favicon: null
layout_spectrum: 0.26245567156001925
typography_spectrum: 0.04679938708432019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8528772767167538
  lightness: 0.3447198395151645
  saturation: 0.3794501181691885
  rhythmicContrast: 0.40358466655015945
purpose: []
