name: becwilliamslife
favicon: null
layout_spectrum: 0.26245567156001925
typography_spectrum: 0.04679938708432019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d35d13'
    - '#c40030'
    - '#ffffff'
    - '#e08f5c'
    - '#ca2b23'
  brandStrength: 0.8528772767167538
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.40358466655015945
purpose: []
